import type { Metadata } from 'next'

import './globals.css'
import React from "react";
import {geist, passionOne} from "@/lib/fonts";


export const metadata:Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${passionOne.variable} ${geist.variable} antialiased`}>{children}</body>
    </html>
  )
}
